#theme: jekyll-theme-minimal
#title: Filip Tokarski
#logo: /images/web_photo.jpg


title: Filip Tokarski 
#author: Your Name # Your name 
#email: your-email@domain.com # your email shown in the footer
#url: http://huangyz.name/moving/ # this is your site's root address.
#description: > # this means to ignore newlines until "show_excerpts:"
#  A clean and minimalist theme for Jekyll.
#favicon: "./favicon.ico" # set the favicon of the site 

#show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://ftokarski.github.io/images/web_photo.jpg" # avatar in about page
#  about_you: a short description about you. # short description about you in about page
#  date_format: "%b %d" # date format of posts in home page
#  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

# Build settings
theme: huangyz0918/moving
